"""The manuscript data bundle: provenance on every file, MANIFEST from CLAIMS.

The bundle's whole claim is that a reader can re-run a command and get the same
bytes. That is only true if every file says which command, at which commit,
against which corpus — so the header is asserted here rather than eyeballed.
"""

from __future__ import annotations

import inspect
from pathlib import Path

import pytest

from vetoworld.commands.emit import registry
from vetoworld.register import bundle as B
from vetoworld.register import manifest as M
from vetoworld.register import markdown as MD


@pytest.fixture(scope="module")
def built(tmp_path_factory):
    out = tmp_path_factory.mktemp("mdata")
    B.build(out)
    return out


def test_EVERY_REGISTERED_ARTIFACT_LANDS_IN_THE_BUNDLE(built):
    """A bundle missing an artifact is a bundle the skeleton silently writes
    around. The set is taken from `emit.registry()`, so a new artifact joins
    the bundle without anyone remembering to add it."""
    want = set(registry())
    got = {p.stem for p in (built / "register").glob("*.txt")}
    assert want == got, f"missing {want - got}, unexpected {got - want}"


def test_EVERY_FILE_CARRIES_ITS_PROVENANCE(built):
    """**A file without a header is indistinguishable from a paste**, which is
    the transcription problem the bundle exists to end."""
    for path in sorted((built / "register").glob("*.txt")):
        head = path.read_text()[:700]
        assert "generated by   vworld emit" in head, path.name
        assert "commit " in head and "corpus " in head, path.name
        assert "Recompute this file by re-running" in head, path.name


def test_THE_MANIFEST_BINDS_EVERY_REGISTERED_CLAIM(built):
    """**Cite the fid, never the number.** Every claim in the register must
    appear, or the skeleton has a figure it cannot cite — and a figure it
    cannot cite is one it will quote from memory, which is the failure the
    bundle was written to prevent."""
    from vetoworld.register.claims import CLAIMS

    text = (built / "MANIFEST.md").read_text()
    missing = [c.fid for c in CLAIMS if c.fid not in text]
    assert not missing, f"claims absent from MANIFEST: {missing}"
    assert len(CLAIMS) >= 22


def test_THE_MANIFEST_RECOMPUTES_RATHER_THAN_QUOTING_ITSELF():
    """A manifest that read `Claim.value` back would agree with the paper
    whatever the corpus said. Each row is recomputed through `Claim.emit`, and
    the agreement column is the result of that comparison."""
    src = inspect.getsource(M.rows)
    assert "c.emit()" in src, "the manifest must call the emitter"
    assert "got == c.value" in src, "and compare it to the published literal"

    data = M.rows()
    assert data and all(r["agrees"] for r in data), (
        "a registered figure no longer recomputes: "
        f"{[r['fid'] for r in data if not r['agrees']]}")


def test_THE_FUNCTION_COLUMN_IS_CITABLE_not_a_lambda():
    """Every `Claim.emit` is a lambda, so `__qualname__` renders `<lambda>` for
    all of them — not a citable function and not locatable by a reader. The
    column carries the fid's address in the register instead."""
    for r in M.rows():
        assert "<lambda>" not in r["function"], r
        assert r["function"] == f"register/claims.py::{r['fid']}"


def test_SUPERSEDED_NUMBERS_ARE_RECORDED_not_silently_fixed(built):
    """**Rule 4.** Where a number quoted in planning differs from the emitted
    one, both appear. These are corrections-section material, and the spec's own
    'all 13' is the sharpest instance."""
    text = (built / "MANIFEST.md").read_text()
    assert "Superseded numbers" in text
    assert "corrections count" in text and "13" in text
    for what, quoted, _fn, _why in M.SUPERSEDED:
        assert what in text and quoted in text


def test_THE_BUNDLE_PATH_SPENDS_NOTHING():
    """**$0, offline, no key.** `tests/test_serving_paths.py` enumerates the
    paths that spend; this must never join them. Asserted against the source
    rather than trusted, because the cheapest time to notice a bundle that
    dialled an endpoint is before it does."""
    from vetoworld.commands import bundle as CMD

    for mod in (B, M, MD, CMD):
        src = inspect.getsource(mod)
        for forbidden in ("Backend", "run_fidelity", "urllib", "requests",
                          "api_key", "HF_TOKEN", "hf_hub_download"):
            assert forbidden not in src, f"{mod.__name__} references {forbidden}"


def test_A_FAILING_EMITTER_IS_SURFACED_not_swallowed():
    """`emit corrections` returns 1 when a ledger row cites a commit that
    cannot be found. A bundle that hid that would ship an unverifiable ledger
    as a verified one, so the exit code is captured and written into the file."""
    text, code = B.capture(lambda: (print("boom"), 3)[1])
    assert text == "boom\n" and code == 3

    def _raises():
        raise RuntimeError("nope")

    text, code = B.capture(_raises)
    assert code == 1 and "EMITTER RAISED" in text


def test_A_DIRTY_TREE_IS_REPORTED_because_it_cannot_be_reproduced():
    """A bundle built from uncommitted changes cannot be rebuilt from its own
    commit hash. That is allowed — drafting against unlanded emitters is
    legitimate — but it must never be mistaken for a citable artifact."""
    src = inspect.getsource(B.provenance) + inspect.getsource(B.header)
    assert "status" in src and "porcelain" in src
    assert "DIRTY" in src

    prov = dict(B.provenance(), tree="DIRTY — uncommitted changes present")
    assert "DIRTY" in B.header("vworld bundle", prov)


def test_AN_EMPTY_VALUE_RENDERS_AS_A_VALUE_not_a_blank():
    """`break.gone` publishes `[]` — "no model breaks any more". Rendered
    blank, a finding reads as an omission."""
    assert "empty" in MD.table(["a"], [[[]]])
    assert MD.table(["a"], [[None]]).count("—") == 1


def test_THE_MARKDOWN_RENDERER_ESCAPES_PIPES():
    """A model id or a rule sentence containing `|` would otherwise split a row
    into extra columns, silently shifting every value after it."""
    out = MD.table(["a", "b"], [["x|y", 1]])
    assert r"x\|y" in out
    #: Count DELIMITERS, not pipe characters — the escaped one is a literal in
    #: the cell and must not be counted as a column boundary.
    row = out.splitlines()[2]
    assert row.replace(r"\|", "").count("|") == 3, row
