"""The manuscript data bundle: every number emitted, none remembered.

`docs/vetoworld-manuscript-data-bundle.md` is the spec. The goal is a
`manuscript-data/` tree the skeleton can be written from without touching the
repo, where **every figure carries the command that produced it**.

**Why this module has to exist at all.** Every register emitter prints to stdout
and returns an exit code; not one of them writes a file, and none stamps
provenance. A shell loop over `vworld emit` would produce text with no commit,
no corpus digest, and no way to tell a stale capture from a fresh one — which is
the transcription problem the bundle was written to end, relocated into a
directory.

**The header is the point.** A file without one is indistinguishable from a
paste, and the whole discipline is that a reader can re-run the command and get
the same bytes. So every file opens with the generating command, the commit, the
corpus digest and the UTC date.

**$0 and offline.** Nothing here serves a cell, holds a key, or reaches the
network. `tests/test_serving_paths.py` enumerates the paths that spend; this is
deliberately not one of them, and a test asserts the bundle path imports no
backend.
"""

from __future__ import annotations

import datetime as _dt
import io
import subprocess
from contextlib import redirect_stdout
from pathlib import Path

__all__ = ["header", "provenance", "write_artifact", "build"]

BUNDLE_DIRS = ("register", "tables", "log-extracts", "exhibits")


def _git(*args: str) -> str:
    r = subprocess.run(["git", *args], capture_output=True, text=True)
    return r.stdout.strip() if r.returncode == 0 else "(unavailable)"


def provenance() -> dict:
    """Commit, corpus digest, cell count and UTC date — computed once per build.

    The corpus digest is `commands/corpus._digest_corpus`, the same function
    `vworld corpus status` reports, so a reader comparing the two is comparing
    one number to itself rather than two implementations of it.
    """
    from ..commands.corpus import _digest_corpus
    from seahaven.eden._shared.corpus import RESULTS

    digest, cells, _bytes = _digest_corpus(RESULTS)
    dirty = bool(_git("status", "--porcelain"))
    return {
        "commit": _git("rev-parse", "HEAD"),
        "commit_subject": _git("log", "-1", "--format=%s"),
        "tree": "DIRTY — uncommitted changes present" if dirty else "clean",
        "corpus_digest": digest,
        "corpus_cells": cells,
        "generated_utc": _dt.datetime.now(_dt.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"),
    }


def header(command: str, prov: dict, *, comment: bool = False) -> str:
    """The provenance block every bundle file opens with.

    **`tree` is reported, not hidden.** A bundle built from a dirty working tree
    cannot be reproduced from its own commit hash, and a reader who cannot tell
    is worse off than one who is told. It is a warning rather than a refusal
    because drafting against uncommitted emitters is a legitimate thing to do —
    it just must not be mistaken for a citable artifact.
    """
    lines = [
        f"generated by   {command}",
        f"commit         {prov['commit']}  ({prov['commit_subject']})",
        f"working tree   {prov['tree']}",
        f"corpus         {prov['corpus_cells']} cells, "
        f"sha256 {prov['corpus_digest'][:16]}…",
        f"generated      {prov['generated_utc']}",
        "",
        "Recompute this file by re-running the command above at that commit.",
        "Nothing here is transcribed; every figure is emitted.",
    ]
    if comment:
        return "\n".join(f"<!-- {ln} -->" if ln else "<!-- -->" for ln in lines)
    return "\n".join(lines)


def capture(fn) -> tuple[str, int]:
    """Run an emitter, returning `(stdout, exit code)`.

    Emitters print and return a status; the bundle needs both. A non-zero code
    is kept and surfaced rather than swallowed — `emit corrections` returns 1
    when a ledger row cites a commit that cannot be found, and a bundle that
    hid that would be shipping an unverifiable ledger as a verified one.
    """
    buf = io.StringIO()
    try:
        with redirect_stdout(buf):
            code = fn()
    except SystemExit as e:                                   # noqa: PERF203
        code = int(e.code) if isinstance(e.code, int) else 1
    except Exception as e:                                    # noqa: BLE001
        return buf.getvalue() + f"\n** EMITTER RAISED: {e!r} **\n", 1
    return buf.getvalue(), int(code or 0)


def write_artifact(out: Path, name: str, fn, prov: dict) -> int:
    """Emit one artifact to `register/<name>.txt` with its header."""
    text, code = capture(fn)
    path = out / "register" / f"{name}.txt"
    path.write_text(
        header(f"vworld emit {name}", prov) + "\n\n" + ("=" * 72) + "\n\n"
        + text + (f"\n** exit code {code} **\n" if code else ""))
    return code


def build(out: Path) -> int:
    """Emit every registered artifact, then the MANIFEST.

    Returns the number of artifacts whose emitter reported failure. The build
    does not stop at the first — a bundle that is 15/16 complete plus a named
    failure is more useful than a traceback, and the caller decides.
    """
    from ..commands.emit import registry
    from .manifest import write_manifest

    out = Path(out)
    for d in BUNDLE_DIRS:
        (out / d).mkdir(parents=True, exist_ok=True)

    prov = provenance()
    if prov["tree"].startswith("DIRTY"):
        print("  WARNING: working tree is dirty — this bundle cannot be "
              "reproduced from its own commit hash.")

    failed = []
    for name, fn in sorted(registry().items()):
        code = write_artifact(out, name, fn, prov)
        status = "ok" if not code else f"EXIT {code}"
        print(f"  register/{name}.txt{'':<{max(0, 28 - len(name))}}{status}")
        if code:
            failed.append(name)

    write_manifest(out, prov)
    print(f"\n  MANIFEST.md written")
    if failed:
        print(f"\n  {len(failed)} emitter(s) reported failure: "
              f"{', '.join(failed)}")
        print("  The bundle is written; those artifacts are NOT citable.")
    return len(failed)
